export const bets = [
  { sport: 'Basketball', bet: 'Stephen Curry Over/Under 29.5 points' },
  { sport: 'Basketball', bet: 'LeBron James Over/Under 25.5 points' },
  { sport: 'Basketball', bet: 'Kevin Durant Over/Under 27.5 points' },
  { sport: 'Basketball', bet: 'Luka Doncic Over/Under 30.5 points' },
  { sport: 'Basketball', bet: 'Giannis Antetokounmpo Over/Under 28.5 points' },
  { sport: 'Basketball', bet: 'Joel Embiid Over/Under 31.5 points' },
  { sport: 'Basketball', bet: 'Jayson Tatum Over/Under 26.5 points' },
  { sport: 'Basketball', bet: 'Damian Lillard Over/Under 24.5 points' },
  { sport: 'Basketball', bet: 'James Harden Over/Under 10.5 assists' },
  { sport: 'Basketball', bet: 'Nikola Jokic Over/Under 12.5 rebounds' },
  { sport: 'Football', bet: 'Patrick Mahomes Over/Under 2.5 passing touchdowns' },
  { sport: 'Football', bet: 'Derrick Henry Over/Under 89.5 rushing yards' },
  { sport: 'Football', bet: 'Davante Adams Over/Under 7.5 receptions' },
  { sport: 'Football', bet: 'Josh Allen Over/Under 280.5 passing yards' },
  { sport: 'Football', bet: 'Justin Jefferson Over/Under 99.5 receiving yards' },
  { sport: 'Football', bet: 'Tyreek Hill Over/Under 1.5 touchdowns' },
  { sport: 'Football', bet: 'Aaron Rodgers Over/Under 250.5 passing yards' },
  { sport: 'Football', bet: 'Travis Kelce Over/Under 8.5 receptions' },
  { sport: 'Baseball', bet: 'Shohei Ohtani Over/Under 1.5 home runs' },
  { sport: 'Baseball', bet: 'Aaron Judge Over/Under 2.5 total bases' },
  { sport: 'Baseball', bet: 'Jacob deGrom Over/Under 7.5 strikeouts' },
  { sport: 'Baseball', bet: 'Mookie Betts Over/Under 1.5 hits' },
  { sport: 'Baseball', bet: 'Juan Soto Over/Under 2.5 RBIs' },
  { sport: 'Baseball', bet: 'Bryce Harper Over/Under 3.5 total bases' },
  { sport: 'Baseball', bet: 'Max Scherzer Over/Under 8.5 strikeouts' },
  { sport: 'Hockey', bet: 'Connor McDavid Over/Under 1.5 points' },
  { sport: 'Hockey', bet: 'Sidney Crosby Over/Under 2.5 shots on goal' },
  { sport: 'Hockey', bet: 'Auston Matthews Over/Under 0.5 goals' },
  { sport: 'Hockey', bet: 'Nathan MacKinnon Over/Under 3.5 shots on goal' },
  { sport: 'Hockey', bet: 'Alex Ovechkin Over/Under 1.5 power play goals' },
  { sport: 'Soccer', bet: 'Lionel Messi Over/Under 1.5 goals' },
  { sport: 'Soccer', bet: 'Cristiano Ronaldo Over/Under 2.5 shots on target' },
  { sport: 'Soccer', bet: 'Neymar Over/Under 3.5 dribbles completed' },
  { sport: 'Soccer', bet: 'Kylian Mbappe Over/Under 2.5 goals' },
  { sport: 'Soccer', bet: 'Erling Haaland Over/Under 4.5 shots on goal' },
  { sport: 'Tennis', bet: 'Novak Djokovic Over/Under 22.5 total games in match' },
  { sport: 'Tennis', bet: 'Rafael Nadal Over/Under 3.5 aces' },
  { sport: 'Freestyle Wrestling', bet: 'Jordan Burroughs Over/Under 8.5 total points scored' },
  { sport: 'Freestyle Wrestling', bet: 'Kyle Dake Over/Under 6.5 takedowns' },
  { sport: 'Freestyle Wrestling', bet: 'David Taylor Over/Under 9.5 match duration in minutes' },
  { sport: 'Freestyle Wrestling', bet: 'Gable Steveson Over/Under 10.5 points scored' },
  { sport: 'Freestyle Wrestling', bet: 'Zain Retherford Over/Under 7.5 takedowns' },
  { sport: 'MMA', bet: 'Israel Adesanya Over/Under 2.5 rounds' },
  { sport: 'MMA', bet: 'Jon Jones Over/Under 3.5 takedowns' },
  { sport: 'MMA', bet: 'Conor McGregor Over/Under 1.5 knockdowns' },
  { sport: 'Boxing', bet: 'Canelo Alvarez Over/Under 7.5 rounds' },
  { sport: 'Boxing', bet: 'Tyson Fury Over/Under 8.5 rounds' },
  { sport: 'Boxing', bet: 'Anthony Joshua Over/Under 2.5 knockdowns' },
  { sport: 'Boxing', bet: 'Deontay Wilder Over/Under 3.5 knockdowns' },
  { sport: 'Boxing', bet: 'Gervonta Davis Over/Under 6.5 rounds' },
  { sport: 'Basketball', bet: 'Devin Booker Over/Under 24.5 points' },
  { sport: 'Football', bet: 'Stefon Diggs Over/Under 85.5 receiving yards' },
  { sport: 'Baseball', bet: 'Vladimir Guerrero Jr. Over/Under 1.5 home runs' },
  { sport: 'Hockey', bet: 'Brad Marchand Over/Under 2.5 shots on goal' },
  { sport: 'Soccer', bet: 'Robert Lewandowski Over/Under 1.5 goals' },
  { sport: 'Tennis', bet: 'Stefanos Tsitsipas Over/Under 3.5 aces' },
  { sport: 'Freestyle Wrestling', bet: 'Frank Chamizo Over/Under 7.5 total points' },
  { sport: 'MMA', bet: 'Charles Oliveira Over/Under 3.5 submission attempts' },
  { sport: 'Boxing', bet: 'Josh Taylor Over/Under 9.5 rounds' },
  { sport: 'Basketball', bet: 'Trae Young Over/Under 26.5 points' },
]

console.log(bets)
